
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1724 1729 1", "1724 1729 2", "1724 1729 3", "1724 1729 4", "1724 1729 5", "1724 1729 6", "1724 1729 7", "1729 1734 8", "1729 1734 9", "1729 1734 10", "1729 1734 11", "1729 1734 12", "1729 1734 13", "1729 1734 14", "1734 1739 15", "1734 1739 16", "1734 1739 17", "1734 1739 18", "1734 1739 19", "1734 1739 20", "1734 1739 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install
      run: |
        cd wkwk
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        sudo apt install -y ffmpeg
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
